// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96SaNax_AlXBnRtsgQHH1E3CAWyHY82o',
    appId: '1:450899909210:web:a0cd6d478cfbef87da5663',
    messagingSenderId: '450899909210',
    projectId: 'ecommerce-b482f',
    authDomain: 'ecommerce-b482f.firebaseapp.com',
    storageBucket: 'ecommerce-b482f.appspot.com',
    measurementId: 'G-LWTVY1W6L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuBiBQveljWWPFRNZ_OSNIg0iqNi1JzZA',
    appId: '1:450899909210:android:4ad26904f255336bda5663',
    messagingSenderId: '450899909210',
    projectId: 'ecommerce-b482f',
    storageBucket: 'ecommerce-b482f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_JxKfQL99slAqhrl9ifhP9GERmrH3RU',
    appId: '1:450899909210:ios:70e837c38b49e850da5663',
    messagingSenderId: '450899909210',
    projectId: 'ecommerce-b482f',
    storageBucket: 'ecommerce-b482f.appspot.com',
    iosBundleId: 'com.example.ecommerceappcrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_JxKfQL99slAqhrl9ifhP9GERmrH3RU',
    appId: '1:450899909210:ios:70e837c38b49e850da5663',
    messagingSenderId: '450899909210',
    projectId: 'ecommerce-b482f',
    storageBucket: 'ecommerce-b482f.appspot.com',
    iosBundleId: 'com.example.ecommerceappcrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD96SaNax_AlXBnRtsgQHH1E3CAWyHY82o',
    appId: '1:450899909210:web:4f4bbd2994163daeda5663',
    messagingSenderId: '450899909210',
    projectId: 'ecommerce-b482f',
    authDomain: 'ecommerce-b482f.firebaseapp.com',
    storageBucket: 'ecommerce-b482f.appspot.com',
    measurementId: 'G-SML8PK02XE',
  );
}
